name: Post Cat to X (Every 15 min)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (no tweet)"
        required: true
        default: "true"
        type: choice
        options: ["true", "false"]

permissions:
  contents: write

concurrency:
  group: post-cat
  cancel-in-progress: true

jobs:
  post-cat:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || npm i

      - name: Preflight (check secrets)
        run: |
          node -e "['CAT_API_KEY','TWITTER_APP_KEY','TWITTER_APP_SECRET','TWITTER_ACCESS_TOKEN','TWITTER_ACCESS_SECRET'].forEach(k=>{if(!process.env[k]){throw new Error('Missing '+k)}})"
        env:
          CAT_API_KEY: ${{ secrets.CAT_API_KEY }}
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}

      - name: Run poster
        run: node post-cat.js
        env:
          CAT_API_KEY: ${{ secrets.CAT_API_KEY }}
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          DRY_RUN: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || 'false' }}

      - name: Commit caption state
        if: ${{ success() }}
        run: |
          if [ -f .state/used_captions.json ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .state/used_captions.json
            git commit -m "chore: update caption history [skip ci]" || echo "no changes"
            git push
          else
            echo "No caption state file found; skipping commit."
          fi
