name: Post Cat to X (Every 30 min)

on:
  schedule:
    - cron: "*/30 * * * *"   # 30分ごと
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (no tweet)"
        required: true
        default: "true"
        type: choice
        options: ["true", "false"]

concurrency:
  group: post-cat
  cancel-in-progress: true

jobs:
  post-cat:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci || npm i

      - name: Post a cat image to X
        run: node post-cat.js
        env:
          # Secrets（Settings → Secrets and variables → Actions）
          CAT_API_KEY: ${{ secrets.live_2Db1IQ9XcoS7iClgzp9JkxZxv9K82pA4S4LU9tI595LnniEy5RpGDCDCjRrRP64r }}
          TWITTER_APP_KEY: ${{ secrets.D4tCtvDdD1oCKx5Cm1gd4hOKI }}
          TWITTER_APP_SECRET: ${{ secrets.nbER1eAifbUYK9SCbwXx6TtyhxqlrR7GwPMK94UrgudLzpxlgP }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.1964304988420911104-3IAcoOZ40JPj316YeYlsLzgVqabxkU }}
          TWITTER_ACCESS_SECRET: ${{ secrets.jZf0779uTsLMX62wYwKvpS2MHfVqr1Xw848AKRpf2iWB6 }}
          # 手動実行時だけ DRY_RUN を切り替え（スケジュール実行時は未設定＝false）
          DRY_RUN: ${{ inputs.dry_run }}
